### ISSUE TITLE
Double quote before date below the even title, on home page

### ISSUE THREAD

**Issue by jdecode** [Devtalks-India/devtalks#10]
Double quote before date below the even title, on home page.
![Screenshot from 2020-06-02 15-39-41](https://user-images.githubusercontent.com/37613346/83508423-8ab8f800-a4e7-11ea-8de1-deb58b4856c8.png)

**Comment by sourabhgrover** [comment]
@jdecode @sarabs3 issue is fixed
PR: https://github.com/Devtalks-India/devtalks/pull/12
